//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pro_view.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pro_view.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS grl.tbl_system
        ///(
        ///    scl boolean NOT NULL DEFAULT &apos;false&apos;
        ///);
        ///
        ///delete  from grl.tbl_system;
        ///insert into grl.tbl_system(scl)values(&apos;false&apos;);.
        /// </summary>
        internal static string _10 {
            get {
                return ResourceManager.GetString("_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP FUNCTION IF EXISTS acc.fnc_cin_post(character varying, timestamp without time zone, character varying, character varying);
        ///DROP FUNCTION IF EXISTS acc.fnc_cout_post(character varying, timestamp without time zone, character varying, character varying);
        ///--------------------------------------------------------------------------------------------------------------------------------------------------------------------
        ///--------------------------------------------------------------------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _11 {
            get {
                return ResourceManager.GetString("_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alter table acc.tbl_jor add column IF NOT EXISTS frozen boolean NOT NULL DEFAULT &apos;false&apos;;
        ///alter table acc.tbl_jor add column IF NOT EXISTS closed boolean NOT NULL DEFAULT &apos;false&apos;;
        ///alter table acc.tbl_jord add column IF NOT EXISTS frozen boolean NOT NULL DEFAULT &apos;false&apos;;
        ///alter table acc.tbl_jord add column IF NOT EXISTS closed boolean NOT NULL DEFAULT &apos;false&apos;;
        ///
        ///INSERT INTO grl.tbl_events(id, aname, ename)VALUES (70, &apos;إقفال الحسابات&apos;, &apos;Close Accounting&apos;)on conflict (id) do nothing;
        ///
        ///
        ///DROP FUNCTION IF  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _12 {
            get {
                return ResourceManager.GetString("_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alter table acc.tbl_cind alter column bank_id drop not null;
        ///alter table acc.tbl_coutd alter column bank_id drop not null;
        ///
        ///--DROP FUNCTION acc.fnc_cout_post(character varying, timestamp without time zone, character varying, character varying);
        ///-- DROP FUNCTION acc.fnc_cin_post(character varying, timestamp without time zone, character varying, character varying);
        ///--------------------------------------------------------------------------------------------------------------------------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _13 {
            get {
                return ResourceManager.GetString("_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP VIEW acc.viw_st;
        ///--------------------------------------------------------------------------------------
        ///CREATE OR REPLACE VIEW acc.viw_st AS
        /// SELECT j.chart_id,
        ///    j.debit,
        ///    j.credit,
        ///    j.notes,
        ///    j.jor_id,
        ///    j.creationtime AS date,
        ///    j.doctype_id,
        ///    j.cc1_id,
        ///    j.cc2_id,
        ///    j.branch_id,
        ///    j.company_id,
        ///	j.doc_id,
        ///	j.fyear,
        ///	j.jortype_id,
        ///    d.aname AS doctype_aname,
        ///    d.ename AS doctype_ename
        ///   FROM acc.tbl_jord j
        ///     LEFT JOIN grl.tbl_doctype d ON j.doctype [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _14 {
            get {
                return ResourceManager.GetString("_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP FUNCTION IF EXISTS acc.fnc_jor_insert(character varying, character varying, numeric, text, text, character varying, character varying, character varying, character varying, character varying, timestamp without time zone, character varying, json);
        ///DROP FUNCTION IF EXISTS acc.fnc_jor_update(character varying, character varying, numeric, text, text, character varying, character varying, character varying, character varying, character varying, timestamp without time zone, character varying, json);
        ///DROP F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _15 {
            get {
                return ResourceManager.GetString("_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS grl.tbl_permissions;
        ///-------------------------------------------------------------------------------------------------------------------------------
        ///CREATE TABLE IF NOT EXISTS grl.tbl_permgroup
        ///(
        ///    module_id character varying(2) NOT NULL,
        ///    id character varying(4) NOT NULL,
        ///    sequ smallint not null,
        ///    aname text COLLATE pg_catalog.&quot;default&quot;,
        ///    ename text COLLATE pg_catalog.&quot;default&quot;,
        ///    notes text COLLATE pg_catalog.&quot;default&quot;,
        ///    CONSTRAINT fky_permgroup_module_id  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _16 {
            get {
                return ResourceManager.GetString("_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP FUNCTION IF EXISTS acc.fnc_jorcyc_insert(
        ///	in_id int,
        ///	in_currency_id character varying,
        ///	in_currencyprice numeric,
        ///	in_jortype_id text,
        ///	in_notes text,
        ///	in_cc1_id character varying,
        ///	in_cc2_id character varying,	
        ///	in_jord json);
        ///DROP VIEW IF EXISTS acc.viw_jorcyc_select;
        ///DROP TABLE IF EXISTS acc.tbl_jordcyc;
        ///DROP TABLE IF EXISTS acc.tbl_jorcyc;
        ///--------------------------------------------------------------------------------------------
        ///----------------------------------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _17 {
            get {
                return ResourceManager.GetString("_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP FUNCTION IF EXISTS  acc.fnc_jor_insert(character varying, character varying, numeric, text, text, character varying, character varying, character varying, character varying, character varying, timestamp without time zone, character varying, json);
        ///DROP FUNCTION IF EXISTS  acc.fnc_jor_update(character varying, character varying, numeric, text, text, character varying, character varying, character varying, character varying, character varying, timestamp without time zone, character varying, json);
        ///DROP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _18 {
            get {
                return ResourceManager.GetString("_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP VIEW IF EXISTS acc.viw_st;
        ///DROP VIEW IF EXISTS acc.viw_tb;
        ///--------------------------------------------------------------------------------------
        ///--------------------------------------------------------------------------------------
        ///CREATE OR REPLACE VIEW acc.viw_st AS
        /// SELECT j.chart_id,
        ///    j.debit,
        ///    j.credit,
        ///    j.notes,
        ///    j.jor_id,
        ///    j.creationtime AS date,
        ///    j.doctype_id,
        ///    j.cc1_id,
        ///    j.cc2_id,
        ///    j.branch_id,
        ///    j.company_id,
        ///	j.doc_id,
        ///	j.fyear_id,
        ///	j.jortype_i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _19 {
            get {
                return ResourceManager.GetString("_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- FUNCTION: acc.fnc_chart_delete(character varying, character varying, character varying)
        ///
        ///-- DROP FUNCTION acc.fnc_chart_delete(character varying, character varying, character varying);
        ///
        ///CREATE OR REPLACE FUNCTION acc.fnc_chart_delete(
        ///	in_id character varying,
        ///	in_company_id character varying,
        ///	in_user_id character varying)
        ///    RETURNS SETOF acc.tbl_chart 
        ///    LANGUAGE &apos;plpgsql&apos;
        ///
        ///    COST 100
        ///    VOLATILE 
        ///    ROWS 1000
        ///AS $BODY$
        ///
        ///declare 
        ///	on_parent_id text;
        ///	on_servertime timestamp;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLEIF EXISTS acc.tbl_cin;
        ///
        ///CREATE TABLE acc.tbl_cin
        ///(
        ///    id character varying(10) COLLATE pg_catalog.&quot;default&quot; NOT NULL,
        ///	jor_id character varying(15),
        ///    amoutn numeric NOT NULL DEFAULT 0,
        ///    chart_cin_id text COLLATE pg_catalog.&quot;default&quot; NOT NULL,
        ///    chart_cout_id text COLLATE pg_catalog.&quot;default&quot; NOT NULL,
        ///    notes text COLLATE pg_catalog.&quot;default&quot;,
        ///    paytype_id smallint NOT NULL,
        ///    checkcardno text COLLATE pg_catalog.&quot;default&quot;,
        ///    checkcarddate date,
        ///    sorno text COLLATE  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS acc.tbl_cin;
        ///
        ///CREATE TABLE acc.tbl_cin
        ///(
        ///    id character varying(10) COLLATE pg_catalog.&quot;default&quot; NOT NULL,
        ///	sequ int NOT NULL,
        ///    jor_id character varying(15) COLLATE pg_catalog.&quot;default&quot;, 
        ///	notes text,
        ///    posted boolean NOT NULL DEFAULT false,
        ///    frozen boolean NOT NULL DEFAULT false,
        ///    closed boolean NOT NULL DEFAULT false,
        ///    creationtime timestamp without time zone NOT NULL,
        ///    createservertime timestamp without time zone NOT NULL,
        ///    createuser_id character v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update grl.tbl_paytype set aname = &apos;نقداً&apos; where id = 1;
        ///DROP FUNCTION IF EXISTS acc.fnc_cin_insert(character varying, text, character varying, character varying, character varying, character varying, character varying, timestamp without time zone, character varying, json);
        ///DROP FUNCTION IF EXISTS acc.fnc_cin_update(character varying, text, character varying, character varying, character varying, character varying, character varying, timestamp without time zone, character varying, json);
        ///DROP FUNCTION IF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP FUNCTION IF EXISTS  acc.fnc_cout_insert(character varying, text, character varying, character varying, character varying, character varying, character varying, timestamp without time zone, character varying, json);
        ///DROP FUNCTION IF EXISTS  acc.fnc_cout_update(character varying, text, character varying, character varying, character varying, character varying, character varying, timestamp without time zone, character varying, json);
        ///DROP FUNCTION IF EXISTS  acc.fnc_cout_delete(character varying, charac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP FUNCTION IF EXISTS acc.fnc_jor_insert(character varying, character varying, numeric, text, text, character varying, character varying, character varying, character varying, character varying, timestamp without time zone, character varying, json);
        ///DROP FUNCTION IF EXISTS acc.fnc_jor_update(character varying, character varying, numeric, text, text, character varying, character varying, character varying, character varying, character varying, timestamp without time zone, character varying, json);
        ///DROP F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _7 {
            get {
                return ResourceManager.GetString("_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP FUNCTION IF EXISTS acc.fnc_jor_insert(character varying, character varying, numeric, text, text, character varying, character varying, character varying, character varying, character varying, timestamp without time zone, character varying, json);
        ///DROP FUNCTION IF EXISTS acc.fnc_jor_update(character varying, character varying, numeric, text, text, character varying, character varying, character varying, character varying, character varying, timestamp without time zone, character varying, json);
        ///DROP F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _8 {
            get {
                return ResourceManager.GetString("_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP FUNCTION acc.fnc_jor_insert(character varying, character varying, numeric, text, text, character varying, character varying, character varying, character varying, character varying, timestamp without time zone, character varying, json);
        ///DROP FUNCTION acc.fnc_cin_post(character varying, timestamp without time zone, character varying, character varying);
        ///DROP FUNCTION acc.fnc_cout_post(character varying, timestamp without time zone, character varying, character varying);
        ///------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _9 {
            get {
                return ResourceManager.GetString("_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///-- PostgreSQL database dump
        ///--
        ///
        ///-- Dumped from database version 10.4
        ///-- Dumped by pg_dump version 10.5
        ///
        ///-- Started on 2019-02-09 00:55:50
        ///
        ///SET statement_timeout = 0;
        ///SET lock_timeout = 0;
        ///SET idle_in_transaction_session_timeout = 0;
        ///SET client_encoding = &apos;UTF8&apos;;
        ///SET standard_conforming_strings = on;
        ///SELECT pg_catalog.set_config(&apos;search_path&apos;, &apos;&apos;, false);
        ///SET check_function_bodies = false;
        ///SET client_min_messages = warning;
        ///SET row_security = off;
        ///
        ///--
        ///-- TOC entry 15 (class 2615 OID 62187)
        ///-- Name: acc; T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateNewEmptyDatabase {
            get {
                return ResourceManager.GetString("CreateNewEmptyDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19.
        /// </summary>
        internal static string CurrentUpdate {
            get {
                return ResourceManager.GetString("CurrentUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///	
        ///DELETE FROM grl.tbl_companies;	
        ///INSERT INTO grl.tbl_companies(
        ///	id, sequ, aname, ename, creationtime, createuser_id)
        ///	VALUES (&apos;01&apos;, 1, &apos;الشركة الرئيسية&apos;, &apos;Main Company&apos;, &apos;01/01/2019&apos;, &apos;0001&apos;);
        ///	
        ///DELETE FROM grl.tbl_fyears;	
        ///INSERT INTO grl.tbl_fyears(id, sequ, aname, ename, beigndate, enddate,    company_id, branch_id, creationtime,  createuser_id)
        ///	VALUES (&apos;01&apos;, 1, &apos;2019&apos;, &apos;2019&apos;, 
        ///			TO_DATE((select &apos;01/01/&apos;||(select extract(year from (select(current_timestamp))))), &apos;DD/MM/YYYY&apos;),
        ///			TO_DATE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InsertMainDataToNewDatabase {
            get {
                return ResourceManager.GetString("InsertMainDataToNewDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading_gif_icon_18 {
            get {
                object obj = ResourceManager.GetObject("loading-gif-icon-18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lock_128 {
            get {
                object obj = ResourceManager.GetObject("Lock_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LockClose_128 {
            get {
                object obj = ResourceManager.GetObject("LockClose_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LockOpen_128 {
            get {
                object obj = ResourceManager.GetObject("LockOpen_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO grl.tbl_events(id, aname, ename)VALUES (71, &apos;إنشاء تصميم طباعة&apos;, &apos;Create Printing Design&apos;)on conflict (id) do nothing;
        ///INSERT INTO grl.tbl_doctype(id, aname, ename, schema)VALUES (21, &apos;نموذج طباعة&apos;, &apos;Printing Design&apos;, &apos;grl&apos;)on conflict (id) do nothing;.
        /// </summary>
        internal static string Printing {
            get {
                return ResourceManager.GetString("Printing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from grl.tbl_audit;
        ///delete from acc.tbl_cind;
        ///delete from acc.tbl_cin;
        ///delete from acc.tbl_coutd;
        ///delete from acc.tbl_cout;
        ///delete from acc.tbl_jord;
        ///delete from acc.tbl_jordedit;
        ///delete from acc.tbl_jor;
        ///delete from acc.tbl_joredit;
        ///delete from grl.tbl_currenciesedit;
        ///update grl.tbl_currencies set edit = 0;
        ///delete from grl.tbl_ex;
        ///delete from grl.tbl_fyearsedit;
        ///delete from grl.tbl_fyears;
        ///delete from grl.tbl_rep;
        ///delete from grl.tbl_repd;
        ///delete from grl.tbl_stores;
        ///delete from grl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResetData {
            get {
                return ResourceManager.GetString("ResetData", resourceCulture);
            }
        }
    }
}
